About
DudaYura/team-project pull request #22
Opened 2022-06-11 20:08 UTC by vitaliynykonenko

For checking

2022-06-11 20:15 UTC, DudaYura approved these changes

2022-06-11 20:17 UTC, DudaYura requested changes
изменить название файла с иконками

2022-06-11 21:15 UTC, vitaliynykonenko commented
виправив

2022-06-12 06:09 UTC, DudaYura approved these changes

2022-06-12 06:09 UTC, merged